
Items = [
{'asin': u'B00BAVCD8A', 'name': u'Save Rock And Roll', 'category_id': 124, 'description': u'Description:  FALL OUT BOY SAVE ROCK AND ROLL (F), ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/518PwND9ZwL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/518PwND9ZwL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/518PwND9ZwL.jpg', 'brand': None, 'list_price': u'$13.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B00BAVCD8A%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB00BAVCD8A'}
{'asin': u'B0029358GM', 'name': u'Wilco (The Album)', 'category_id': 124, 'description': u'Description:  WILCO THE ALBUM, ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51nIFE57veL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51nIFE57veL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51nIFE57veL.jpg', 'brand': u'Wilco', 'list_price': u'$18.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B0029358GM%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB0029358GM'}
{'asin': u'B00QXT6MCM', 'name': u'First Kiss (Explicit)', 'category_id': 124, 'description': u'Description:  KID ROCK FIRST KISS, ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51Sdn4B8R%2BL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51Sdn4B8R%2BL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51Sdn4B8R%2BL.jpg', 'brand': u'KID ROCK', 'list_price': u'$18.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B00QXT6MCM%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB00QXT6MCM'}
{'asin': u'B017NSI60W', 'name': u'Rocket the Album', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51wfy6LzeCL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51wfy6LzeCL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51wfy6LzeCL.jpg', 'brand': None, 'list_price': u'$12.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B017NSI60W%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB017NSI60W'}
{'asin': u'B0000061RD', 'name': u'Rock and Roll Doctor: A Tribute to Lowell George', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/514V80XDQKL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/514V80XDQKL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/514V80XDQKL.jpg', 'brand': u'ROCK N ROLL DOCTOR', 'list_price': u'$11.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B0000061RD%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB0000061RD'}
{'asin': u'B00004REQY', 'name': u'Classic Albums - Bob Marley and the Wailers: Catch a Fire', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51TVMMK414L._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51TVMMK414L._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51TVMMK414L.jpg', 'brand': None, 'list_price': u'$9.99', 'offers': u'http://www.amazon.com/gp/offer-listing/B00004REQY%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB00004REQY'}
{'asin': u'B004G1E33Y', 'name': u'Racing Father Time', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51KjTJbdCvL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51KjTJbdCvL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51KjTJbdCvL.jpg', 'brand': None, 'list_price': u'$4.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B004G1E33Y%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB004G1E33Y'}
{'asin': u'B0028ER4QE', 'name': u'The Doors (180 Gram Vinyl)', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51%2BXbSJxd3L._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51%2BXbSJxd3L._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51%2BXbSJxd3L.jpg', 'brand': u'Doors', 'list_price': u'$24.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B0028ER4QE%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB0028ER4QE'}
{'asin': u'B000002C1C', 'name': u'Spawn: The Album (1997 Film)', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/41H5dwMniXL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/41H5dwMniXL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/41H5dwMniXL.jpg', 'brand': None, 'list_price': u'$7.99', 'offers': u'http://www.amazon.com/gp/offer-listing/B000002C1C%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB000002C1C'}
{'asin': u'B002GNOMJ4', 'name': u'Album [Vinyl]', 'category_id': 124, 'description': u'Description:  Brand Name: WEA CORP Mfg#: 744861601012, Shipping Weight: 1.00 lbs, Manufacturer: TRUE PANTHER SOUNDS/ADA, Genre: Popular Music, All music products are properly licensed and guaranteed authentic., ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51CxM9nqcdL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51CxM9nqcdL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51CxM9nqcdL.jpg', 'brand': None, 'list_price': u'$17.98', 'offers': u'http://www.amazon.com/gp/offer-listing/B002GNOMJ4%3FSubscriptionId%3DAKIAILWBOQWYSA3CLRYQ%26tag%3Ddanthepunman-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D386001%26creativeASIN%3DB002GNOMJ4'}
{'asin': u'B0018YDQRG', 'name': u'Planet Rock: The Album (180 Gram Vinyl)', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/613zKLstg-L._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/613zKLstg-L._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/613zKLstg-L.jpg', 'brand': None, 'list_price': u'$24.14', 'offers': None}
{'asin': u'B0013V2UGC', 'name': u'Album', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51VoWBzpaML._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51VoWBzpaML._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51VoWBzpaML.jpg', 'brand': u'EATER', 'list_price': u'$22.99', 'offers': None}
{'asin': u'B00001SIF8', 'name': u'Rock: Train Kept a Rollin', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51HEcAHS3vL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51HEcAHS3vL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51HEcAHS3vL.jpg', 'brand': None, 'list_price': u'$24.98', 'offers': None}
{'asin': u'B00005RETE', 'name': u"Best 80's Modern Rock Album", 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51HCLXvQnnL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51HCLXvQnnL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51HCLXvQnnL.jpg', 'brand': None, 'list_price': u'$30.99', 'offers': None}
{'asin': u'B001DPC4SM', 'name': u'Purple Rain [180 Gram Vinyl]', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51WSAG1qvML._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51WSAG1qvML._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51WSAG1qvML.jpg', 'brand': u'OST/PRINCE', 'list_price': u'$24.98', 'offers': None}
{'asin': u'B00005B36H', 'name': u'Lateralus', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/518y9yUOlNL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/518y9yUOlNL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/518y9yUOlNL.jpg', 'brand': u'Volcano', 'list_price': u'$11.99', 'offers': None}
{'asin': u'B000005J80', 'name': u'Schoolhouse Rock! Rocks', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/5102HFZPX5L._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/5102HFZPX5L._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/5102HFZPX5L.jpg', 'brand': None, 'list_price': u'$13.96', 'offers': None}
{'asin': u'B000003TAW', 'name': u'Weezer (Blue Album)', 'category_id': 124, 'description': u'Description:  WEEZER (BLUE ALBUM) MUSIC, ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51qKps-14fL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51qKps-14fL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51qKps-14fL.jpg', 'brand': u'MUSIC', 'list_price': u'$5.50', 'offers': None}
{'asin': u'B00006L736', 'name': u'Best of Bowie', 'category_id': 124, 'description': u'Description:  Brand Name: WEA CORP Mfg#: 00024008, Shipping Weight: 0.20 lbs, Manufacturer:, Genre: Popular Music, All music products are properly licensed and guaranteed authentic., ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/51D52DaRazL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/51D52DaRazL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/51D52DaRazL.jpg', 'brand': u'Emm/Virgin', 'list_price': u'$11.98', 'offers': None}
{'asin': u'B00001SIES', 'name': u'Showbiz', 'category_id': 124, 'description': u'Description:  ', 'created_by': u'Category', 'small_image': u'http://ecx.images-amazon.com/images/I/41GQHBYYEZL._SL75_.jpg', 'medium_image': u'http://ecx.images-amazon.com/images/I/41GQHBYYEZL._SL160_.jpg', 'large_image': u'http://ecx.images-amazon.com/images/I/41GQHBYYEZL.jpg', 'brand': u'Muse', 'list_price': u'$7.98', 'offers': None}
]
